language: java
sudo: false
install: true
jdk:
- oraclejdk8
dist: trusty
before_install:
- chmod +x gradlew
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
  - "$HOME/.gradle"
  - ".gradle"
before_deploy: "./gradlew prepareUpload"
deploy:
- provider: releases
  api_key:
    secure: 60bzi0klhwahl/xnQYCvf01p76Gj3Yx5DIIr437XgETgu4M2XJqBW3ya+7CyPdzmy/wns2QROb/J0ly6SDNsMM9e6dfNVtImA8q7+p1GniZ7CLAmneSReGQxz68uRbWqgPUPO960ituV8WkZFGUJk6o17H5mXkXnYVYul5S7dwqh6CbLwyGXHIxeRO67cx3/Enx/XFdi4WbfMuz+V6seTWI3e/SVV4aQgVPkWQJn31fsRIWliwfQzZgwDo1iN4vrC13MA2sMk7vJt1TJTER0A2bkWD3bn2/K2WMFRnlefAAmhRi/Vv2kkGOySp6/Wty7IicD6mEzpGS7i7tF41/wO/PakFwTTzmR6eVJnC5W/TlmXAeGmsdnXM6tHUc62u5gTAneeo8UE3BcuKibAQgRQIQ7Eb09UXAsue4xchraW8zen46I32k0OBTYMeGewBYazfsgH4WPZwuiJrYNwR2PqATnfKucTFC0R6bxB3UeV5DrPbi0ryGOKfOQS/F05W01nn/djNvtt8Il5XGYeF7rwRei/HF36IO9kxK8uNCT0GnkMYFtbpaLqznyQNw2pz6CyT0PopZzsxKEZMHKZXdOzTgMbBw8HWPhnrlXA+adu3vW803Gka+R/pQ3rG1rt54l5uh/8sdWx1x0ixyKvdYIP17UNszlY+ltgO0HonWJ09M=
  file: "jvm/build/libs/kotlog.jar"
  skip_cleanup: true
  on:
    tags: true
    repo: kotlinmp/Kotlog
- provider: bintray
  file: .bintraydescriptor.json
  user: ranolp
  key:
    secure: "FVlTR8HgFHxlygf8Fb/fZ2LfAg83SIobOG/3Hn4K2KuynIavGpy8taSr7y10tJhBg06x4hU7kMU6C8iiTGOAuixCs7YirRP1rkQ8ZodDLXtgfwmImfWUgrqpJJOgci+/dybGwQoeGAX2PhOlqaNscSxRfr/hkACV6wft+iGz821SFdmKEKQxfRXG0WtlRoH/bJVTDU2qpEPmHDhhcw1xFu6b+1VnRDHwr38V1ME5UJFUBbhST3YltaJsAB1U/Kl19QE+Sun6DodtlYg+NjHqMY5SIBflVg9BQJKhjFJsOPxSIPGYDgv3FLF3LJihjrIfstemKVdr6mrojsYHuo/gG2FSkc8wmJLzF6zz98dff4kq+kzzq1rlxFgp0LHkq/d42fErKyqyAZaD5JM4jFCPo3LnHVW22+uHPv19FTNvcd1XPQ1BIdqsoGQ0LHrXowhK9YiikbF3GWA/YGDZdB3by9ci6dj/ZQEKOGz2EgnYFLIJPBEAJ6R0MMCkl7A9XMxD+ZHLDctAP5kGZxatr9d4g1AddS75syx3IbpDM2CIYt21gcOaUWvRydes4g3g2oVaKRAEAIRiPTikk29Lbf1hhQCqCvO+hKBKTgaOnIXcKvbAkT5aXYropMszYRrmK9pWzRBDM8cZCAE0LIrLorxb5ciJ1QKtSuB1COVlcip2aeo="
  skip_cleanup: true
  on:
    tags: true
    repo: kotlinmp/Kotlog
