language: java
sudo: false
install: true
jdk:
- oraclejdk8
dist: trusty
before_install:
- chmod +x gradlew
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
  - "$HOME/.gradle"
  - ".gradle"
before_deploy: "./gradlew prepareUpload"
deploy:
- provider: releases
  api_key:
    secure: Qa9w8LZM7ssHnOd4QGAnWgxWkDH59iJmNCGfatMdnCcv4Y4mJ646Q9eyErUoT1tc/QYVTCXViLfDypcA2n7McC3iaaqY5MTTORE+CyhCqN14l+57750EbD85EvdZg3CqRpKVXMPf6Tk26YLo/NZL3a1On0cHPh/lE8Lg4al93NScS1K9SXGYQHlhXCYOVsQYXmXV0YETkXqVZODgZUyRI1Vnii71uqspoI8qekNdkQf2UhRyK+6DwmjGIJP6yK3N77Smj9crVdrhbwEyifXtmzcpRjjUYQm9cGxwPQhU64J8y5jAM5MecqWTtRnmZtSBBnkMyG8Qojku1HD50T16vDcF3ZQOufkz2TAssK0wwef+PYawHaVpZiIzQjhXZajn1ArNfTf4RdbGLRh/A4OifBJRFV97VZGfqzp79EwDH2wbP1uxRJSL9IbQEe3bKMJV3vh20E+IO+YT2JH/Utqro9o7crEVMKNlbkx+SJkDchU5WNxIpCoxrAr4kssw3EwX2vZfIR4vzN4NCgQx4jtLZO1XLvQsznYHYBy+evv4KXnDZeqmRkNWmWAsrPryEu4yVgsCvW30IWqZQ04TNQBaddIk7RMa8nWj/T51jACR3fDSU6w/i1IlOMsxQXdQtgBBuRQKSowN65XgGkaS6lOkSYxGSgwFdJyiRyqoxvXC2uQ=
  file: "jvm/build/libs/kotlog.jar"
  skip_cleanup: true
  on:
    tags: true
    repo: kotlinmp/Kotlog
- provider: bintray
  file: .bintraydescriptor.json
  user: ranolp
  key:
    secure: "bfSvvAFY+jn9S6iKZUKezU0SOL9BxA1eYh76ZD/iSbmtithp+ROE9IVzwIpSaM62vDbMqoBXyO6A2u9gdxBywV/0jSBPw1SyRPzezEiKDpFxZJLaqEnDmAz4ZzVwW8jd0ltvmLtP3KVX3+sWg4kAywyoZGZqeYSVqUcWnViUbes1Yoiq2NPAhZ8Dfout2u3NYzsSyx5fJq3xOxhDyhS5by9D3BHofNfD72iyhCTHZbOdGGMfe2Cpu611GG2eL9bQuPgIAVob1MjRGHFZwsyXsitsWAVe8AegbfM3KOxxg7WRi4mgHLkg5SEAtfq8/yCOYDDywWKWdGzXQ+LeaSiIkX7rDjKhq9V9v7/t1YZN9gsEs35Yc71twkHgQqQkUxTsXZTAdhElcGdI9NxbGO035nCqMJjGGnUsZd0K2vl1lfnrK2g9/nGqljISadatjBExFIjeJkry6apmB4EbpKrdSdycDU69ArfkA4ZkrtFUbGMhzG2dtgnHv9mOnHecg6mOa9wduNJ9MAsmcv0a97qB85xV9vpRrPDOyM3/Mzv3quj2J11mzehFE2hEMG7EN4MwP1L6/lYawhyuIyLUjIQakVymPPFEarXcVRDMjFavDiOJGtX7BZRioB1mOZbWHShmuDCmZdJ235ILaVMAJrsZCr99jSf12jvGhHVnh3Xj9LA="
  skip_cleanup: true
  on:
    tags: true
    repo: kotlinmp/Kotlog
